### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by Shaun-Fong** [zonkosoft/BlendyPose#1]
閿欒: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendy_pose.py", line 119, in run_body
    import cv2
ModuleNotFoundError: No module named 'cv2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendy_pose.py", line 377, in execute
    if context.scene.settings.body_tracking: run_body("None")
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendy_pose.py", line 124, in run_body
    install()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blendy_pose.py", line 59, in install
    subprocess.check_call([sys.executable, "-m", "ensurepip"])
  File "F:\Blender Foundation\Blender 2.83\2.83\python\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['F:\\Blender Foundation\\Blender 2.83\\blender.exe', '-m', 'ensurepip']' returned non-zero exit status 1.

location: <unknown location>:-1

**Comment by zonkypop** [comment]
Have you tried updating Blender to a new version? It has been tested with Blender 2.9 +

**Comment by Shaun-Fong** [comment]
> Have you tried updating Blender to a new version? It has been tested with Blender 2.9 +

Same result at 2.9.0 . Did I missing something? opencv??

**Comment by Aurosutru** [comment]
Have the same error on Blender 2.93 but 2.92 works fine.

Great work here.

**Comment by zonkypop** [comment]
Sorry for being a bit late on this. Does it work for you now? Looks like Blender has changed a few things between 2.9.2. and 2.9.3 - it might take around a minute to load the first time you run it

**Comment by Aurosutru** [comment]
This is late too.

Tried in Blender 2.93 again with the latest version (0.2 ?) but the following errors resulted:
-------------
> C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py:434
rna_uiItemR: property not found: Settings.body_tracking

C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py:434
rna_uiItemR: property not found: Settings.body_tracking

C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py:434
Using file:  <_PropertyDeferred, <built-in function StringProperty>, {}>
Python: Traceback (most recent call last):
  File "C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py", line 353, in execute
    if context.scene.settings.body_tracking: run_body(context.scene.settings.file_path)
  File "C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py", line 136, in run_body
    else: cap = cv2.VideoCapture(file_path)
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'VideoCapture'
> Overload resolution failed:
>  - Can't convert object of type '_PropertyDeferred' to 'str' for 'filename'
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)
>  - Argument 'index' is required to be an integer
>  - VideoCapture() missing required argument 'apiPreference' (pos 2)


location: <unknown location>:-1
rna_uiItemR: property not found: Settings.body_tracking

C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py:434
rna_uiItemR: property not found: Settings.body_tracking

C:\Users\TomMoriarty\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blendy_pose.py:434
---------
The script downloaded mediapipe and opencv again.

**Comment by Aurosutru** [comment]
Please don't mind the odd formatting in the above comment.  Github handles quotes in a non-intuitive way.

**Comment by Aurosutru** [comment]
Note that the above errors occurred when clicking the Blendy Pose "Video File" button in 2.93 and selecting a video that works in Blendy Pose in Blender 2.92.

**Comment by zonkypop** [comment]
It should be working now in Blender 2.93.1

**Comment by sparshgarg23** [comment]
when clicking on camera,i got the error no module named cv2.My blender version is 3.0.0
