### ISSUE TITLE
Fail To Generate Bones (PosePipe)

### ISSUE THREAD

**Issue by LuisFer-DesignForAll** [zonkosoft/BlendyPose#11]
I have inserted the **PosePipe** plugin (https://github.com/SpectralVectors/PosePipe), it works perfectly, it has correctly transmitted the motion capture. (To see photo 01)

I understand that mocap needs a skeleton (rig) to associate to an avatar, I have added the skeleton without problem [Add --> Armature --> Human (MetaRig)]. The skeleton added. (To see photo 02)

Then, I have pressed the "**Generate Bones**" button, to join between the mocap points and the skeleton, they get an error: (To see photo 03)

> Python: Traceback (most recent call last):
>   File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\PosePipe.py", line 557, in execute
>     bpy.data.armatures['Armature'].name = "Body_Skeleton"
> KeyError: 'bpy_prop_collection[key]: key "Armature" not found'
> 
> location: <unknown location>:-1

Whit Blender 2.93.9 LTS

I hope your help, I'm not a Blender expert, I love learning.

Thank you very much.
LuisFer

Photo 01: Mocap OK

![image](https://user-images.githubusercontent.com/82392126/165553034-e6b6a0ed-ba6b-4e75-9e24-a3a2375b1647.png)

Photo 02: The skeleton added and the "**Generate Bones**" button

![image](https://user-images.githubusercontent.com/82392126/165552569-1f1618b3-28d5-42ef-b745-495d696c8853.png)

Photo 03: Error

![image](https://user-images.githubusercontent.com/82392126/165554265-8acba0db-5b99-4dd2-8edd-643fe0539670.png)

**Comment by LuisFer-DesignForAll** [comment]
I'm doing an experiment on mocap to avatar conversion, with any free software:

- Mocap: Run all three at once (Body, Hands and Face)
- Input: Through the video file, and also from the direct camera
- Generate: Joins between mocap and skeleton or avatar, in a way to connect the two
- Output: Avatar that moves as motion captured (mocap)
- Operating system: Windows (Option: macOS)

I hope your help.

Anyway, you can add some related links.

Thank you very much,
LuisFer

**Comment by LuisFer-DesignForAll** [comment]
Hello!!

The "Generate bones" button works perfectly.

We simply need to create other new scene, then yes.

It's a little weird, but hey, it's a little trick to get it right. So you would let know it.

We close issue, it is solved.

Thank you 😃
LuisFer

**Comment by tmanallen** [comment]
I know this is closed, but, qq, did you map the animations to the rig, if so, could you explain how, been trying this for the last few days.

**Comment by tmanallen** [comment]
> Hello!!
> 
> The "Generate bones" button works perfectly.
> 
> We simply need to create other new scene, then yes.
> 
> It's a little weird, but hey, it's a little trick to get it right. So you would let know it.
> 
> We close issue, it is solved.
> 
> Thank you 😃 LuisFer

I know this is closed, but, qq, did you map the animations to the rig, if so, could you explain how, been trying this for the last few days.
