### ISSUE TITLE
Thoughts on applying this mocap to a Blender mesh object

### ISSUE THREAD

**Issue by Aurosutru** [zonkosoft/BlendyPose#2]
Any ideas on the best way to animate a Blender character with this mocap data?

Some work on BVH output from mocap was done in python at:  https://github.com/KevinLTT/video2bvh

A more recent conversion using bones is at:  https://blog.tensorflow.org/2020/05/pose-animator-open-source-tool-to-bring-svg-characters-to-life.html

The following might be of interest for getting angles with numpy that could be applied to bones:  https://www.youtube.com/watch?v=EgjwKM3KzGU

A solution within MediaPipe would be ideal.

**Comment by hzc54188** [comment]
i can't use【ESQUELETOOK_mediapipe_blender_v1.py】
would you teache me ,sir?

**Comment by Aurosutru** [comment]
Hi,
I'm not a programmer, at least not in Python, so I cannot offer much help.  However some good work with mediapipe in Blender can be found here:  https://www.patreon.com/posts/dev-preview-and-53711794
Carlos is very helpful, but from a recent comment may be busy learning C++.  Maybe he will finish his Blender add-on with hands and smooth motions soon.
Other good work is being done with Omniverse to bring lip sync animation into Blender.
Hope that helps.
